apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sysmon
resources:
  - base/namespace.yaml
  - base/sysmon-secrets.yaml
  # - base/postgres.yaml
  - base/backend-sqlite.yaml
  - base/frontend.yaml
  # base/ingress.yaml  # uncomment when you have an Ingress controller
images:
  - name: sysmon-frontend
    newTag: v6
  - name: sysmon-backend
    newTag: working # Use known working image instead of 'latest' which is crashing
configMapGenerator:
  - name: sysmon-frontend-nginx
    files:
      - default.conf=config/frontend-nginx.conf
generatorOptions:
  disableNameSuffixHash: true
