# Generated by Django 4.2.9 on 2026-03-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField()),
                ('cpu_count_physical', models.IntegerField()),
                ('cpu_count_logical', models.IntegerField()),
                ('cpu_freq_current', models.FloatField(blank=True, null=True)),
                ('cpu_freq_max', models.FloatField(blank=True, null=True)),
                ('ram_total', models.BigIntegerField()),
                ('ram_used', models.BigIntegerField()),
                ('ram_available', models.BigIntegerField()),
                ('ram_percent', models.FloatField()),
                ('disk_total', models.BigIntegerField()),
                ('disk_used', models.BigIntegerField()),
                ('disk_free', models.BigIntegerField()),
                ('disk_percent', models.FloatField()),
                ('net_bytes_sent', models.BigIntegerField()),
                ('net_bytes_recv', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('cpu_percent', models.FloatField()),
                ('memory_mb', models.FloatField()),
                ('status', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='monitor.systemsnapshot')),
            ],
            options={
                'ordering': ['-cpu_percent'],
            },
        ),
        migrations.CreateModel(
            name='GPUSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('load', models.FloatField()),
                ('memory_used', models.BigIntegerField()),
                ('memory_total', models.BigIntegerField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='monitor.systemsnapshot')),
            ],
        ),
    ]
