apiVersion: v1
kind: Service
metadata:
  name: sysmon-backend
  namespace: sysmon
  labels:
    app: sysmon-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: sysmon-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysmon-backend
  namespace: sysmon
  labels:
    app: sysmon-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sysmon-backend
  template:
    metadata:
      labels:
        app: sysmon-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: backend
          image: sysmon-backend:working
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DEBUG
              value: "False"
            - name: SECRET_KEY
              value: "k8s-dev-change-in-prod-use-secret"
            # SQLite mode — no Postgres needed
            - name: DATABASE_ENGINE
              value: "django.db.backends.sqlite3"
            - name: DATABASE_NAME
              value: "/app/data/db.sqlite3"
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /api/live/
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/live/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
      volumes:
        - name: sqlite-data
          emptyDir: {}
